name: job-listings-analyzer
channels:
  - defaults
dependencies:
  - python=3.8
  - pandas=1.3.3
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - wordcloud=1.8.1
  - geopandas=0.10.2
  - geopy=2.2.0
  - requests=2.26.0
  - pip:
    - jupyterlab==3.0.14

